### ISSUE TITLE
Resising Title Screen Breaks Menu

### ISSUE THREAD

**Issue by Crazy-Ginger** [No-Team30/ENG1#2]
If the user resizes the menu screen the menu no longer functions forcing the user to restart. 

Steps to recreate:
1. Launch game
2. Drag screen from one corner to resize

**Comment by NoSuchThingAsRandom** [comment]
Yeah that's probably because the resize function is unimplemted.

**Comment by Crazy-Ginger** [comment]
Are we allowing resizing manually or should we enforce it with the settings menu?

**Comment by NoSuchThingAsRandom** [comment]
Honestly, I don't think we need to bother with resizing at this current point?
Like it's not a requirement, and I'm also thinking the same with the settings page, there's nothing saying we have to do it...

**Comment by NoSuchThingAsRandom** [comment]
Fixed in the settings branched
