### ISSUE TITLE
Infiltrator System Selection

### ISSUE THREAD

**Issue by Crazy-Ginger** [No-Team30/ENG1#3]
Once spawned infiltrators unreliably target systems. Sometimes none will attack systems, sometimes only the first will and then get stuck at that system.

Need to find the underlying cause still.

**Comment by NoSuchThingAsRandom** [comment]
Fixed the first infiltrator not targeting systems properly, but is way too effective
However it still doesn't work for multiple systems

**Comment by NoSuchThingAsRandom** [comment]
Fixed the single infiltrator issue
